

version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp $JAR_ARTIFACT_SOURCE .
      - aws ecr get-login --region $REGION | sh
      - docker build -t $ECR_IMAGE .
      - docker tag $ECR_IMAGE:$ECR_TAG $ECR_URL/$ECR_IMAGE:$ECR_TAG
      - docker push $ECR_URL/$ECR_IMAGE:$ECR_TAG
      - chmod +x ecs-deploy
      - chmod +x jq-linux64
      - ./ecs-deploy -c $ECS_CLUSTER -n $ECS_SERVICE -i $ECR_URL/$ECR_IMAGE
  post_build:
    commands:
      - echo Build completed on `date`

