

version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp s3://aws-ecs-akka-http1/akkaHttp-assembly-0.1-SNAPSHOT.jar .
      - aws ecr get-login --region eu-west-2 | sh
      - docker build -t awsecsakkahttp1 .
      - docker tag awsecsakkahttp1:latest 149271426415.dkr.ecr.eu-west-2.amazonaws.com/awsecsakkahttp1:latest 
      - docker push 149271426415.dkr.ecr.eu-west-2.amazonaws.com/awsecsakkahttp1:latest
      - chmod +x ecs-deploy
      - chmod +x jq-linux-64
      - ./ecs-deploy -c mycluster2 -n myservice -i 149271426415.dkr.ecr.eu-west-2.amazonaws.com/awsecsakkahttp1
  post_build:
    commands:
      - echo Build completed on `date`

