

version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - aws ecr get-login --no-include-email --region eu-west-2 | sh
      - docker build -t awsecsakkahttp1 .
      - docker tag awsecsakkahttp1:latest 149271426415.dkr.ecr.eu-west-2.amazonaws.com/awsecsakkahttp1:latest 
      - docker push 149271426415.dkr.ecr.eu-west-2.amazonaws.com/awsecsakkahttp1:latest
  post_build:
    commands:
      - echo Build completed on `date`

